linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - cyclop
  - depguard
  - dogsled
  - dupword
  - durationcheck
  - errcheck
  - exportloopref
  - forbidigo
  - gci
  - goconst
  - gocritic
  - gocyclo
  - godot
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign
  - whitespace

linters-settings:
  gocyclo:
    min-complexity: 40
  cyclop:
    # TODO(sbuerin) fix remaining findings and set to 20 afterwards
    max-complexity: 40
  gci:
    local-prefixes: scm.x5.ru
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
    disabled-checks:
      - appendAssign
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - evalOrder
      - ifElseChain
      - octalLiteral
      - regexpSimplify
      - sloppyReassign
      - truncateCmp
      - typeDefFirst
      - unnamedResult
      - unnecessaryDefer
      - whyNoLint
      - wrapperFunc
      - rangeValCopy
      - hugeParam
  importas:
    no-unaliased: true

  staticcheck:
    go: "1.17"
  stylecheck:
    go: "1.17"
  nestif:
    # minimal complexity of if statements to report, 5 by default
    # TODO(sbuerin) fix remaining findings and set to 5 after:
    # https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/778
    min-complexity: 13

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # List of regexps of issue texts to exclude, empty list by default.
  exclude-rules:
  - linters:
    - gosec
    text: "G108: Profiling endpoint is automatically exposed on /debug/pprof"
  - linters:
    - gosec
    text: "G108: Profiling endpoint is automatically exposed on /debug/pprof"
  # This directive allows the embed package to be imported with an underscore everywhere.
  - linters:
    - revive
    source: _ "embed"
  - linters:
    - revive
    - stylecheck
    path: (test)/.*.go
    text: should not use dot imports
  - linters:
    - revive
    path: test/e2e/shared/defaults.go
    text: "exported: exported const .* should have comment \\(or a comment on this block\\) or be unexported"
  - linters:
    - revive
    text: "var-naming: don't use underscores in Go names;"
    path: .*(api|types)\/.*\/.*conversion.*\.go$
  - linters:
    - stylecheck
    text: "ST1003: should not use underscores in Go names;"
    path: .*(api|types)\/.*\/.*conversion.*\.go$

run:
  timeout: 10m
  build-tags:
  - e2e

  skip-files:
    - "zz_generated.*\\.go$"
  allow-parallel-runners: true
