# permissions for end users to view merges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: merge-viewer-role
rules:
- apiGroups:
  - release.salt.x5.ru
  resources:
  - merges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - release.salt.x5.ru
  resources:
  - merges/status
  verbs:
  - get
