# permissions for end users to edit nativemergerequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nativemergerequest-editor-role
rules:
- apiGroups:
  - release.salt.x5.ru
  resources:
  - nativemergerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - release.salt.x5.ru
  resources:
  - nativemergerequests/status
  verbs:
  - get
