# permissions for end users to view nativemergerequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nativemergerequest-viewer-role
rules:
- apiGroups:
  - release.salt.x5.ru
  resources:
  - nativemergerequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - release.salt.x5.ru
  resources:
  - nativemergerequests/status
  verbs:
  - get
