apiVersion: release.salt.x5.ru/v1alpha1
kind: NativeMergeRequest
metadata:
  name: nativemergerequest-sample1
spec:
  projectID: salt-public/common
  title: trymerge
  sourceBranch: branch2
  targetBranch: build-2023
  autoAccept: true
